### ISSUE TITLE
Support Libs 22.1.1 are broken on Xamarin Stable

### ISSUE THREAD

**Issue by kjeremy** [jamesmontemagno/PagerSlidingTabStrip-for-Xamarin.Android#10]
You might want to hold off on using 22.1.1 for now:

https://forums.xamarin.com/discussion/39261/missing-method-android-runtime-jnienv-startcreateinstance#latest

**Comment by jamesmontemagno** [comment]
Updating to 22.1.1.1 tonight.Thanks!
