### ISSUE TITLE
Is it possible to change a single tabs icon?

### ISSUE THREAD

**Issue by freshive** [jamesmontemagno/PagerSlidingTabStrip-for-Xamarin.Android#12]
Hi James, 

Excellent work this.

Is it possible to access and change a single tabs icon/color?

Use case:

I have a form made up of multiple tabs and I'd like to indicate to the user when all fields are completed on a tab possibly through a green/red icon. 

I do have some idea's but thought I'd check with you before forking.

**Comment by jamesmontemagno** [comment]
It is not supported out of the box, but you could implement a CustomTabProvider to accomplish this.

See this:
https://github.com/jpardogo/PagerSlidingTabStrip/issues/87
