### ISSUE TITLE
Android Support Libraries 22.1.1 broken.

### ISSUE THREAD

**Issue by freshive** [jamesmontemagno/PagerSlidingTabStrip-for-Xamarin.Android#13]
Hi James,

Looks like something is borked in the latest Xamarin Android Support libraries (22.1.1) which your version 1.0.9.1 depends on. I've had to roll back.

https://forums.xamarin.com/discussion/39261/missing-method-android-runtime-jnienv-startcreateinstance

**Comment by jamesmontemagno** [comment]
Updating new version tonight. you will see 1.0.9.2. You can always get older versions as well. In the change log I say when I am updating.
