### ISSUE TITLE
text.Text values not showing in the app,,,

### ISSUE THREAD

**Issue by scallan** [jamesmontemagno/PagerSlidingTabStrip-for-Xamarin.Android#14]
Hi James,

I'm not getting the text.Test values sent into the root and shown in the app when I run your project - for some reason. I thought it might be a configuration issue on my system but I did a complete reinstall of all associated Xamarin packages and it's seems to still be there. I've attached a screen shot. If you have any thoughts I'd really appreciate it!
Thank you for this nice project by the way!

Steve
![text issue](https://cloud.githubusercontent.com/assets/22184/7798750/05835850-02cc-11e5-9ce3-bc3c3acd544d.png)

**Comment by jamesmontemagno** [comment]
Ohhh I think in the theme I set the text color to white, so it is white on white. I can fix this up. Just remove that from the style.xml

**Comment by jamesmontemagno** [comment]
Grab latest sample.

**Comment by scallan** [comment]
Thank you!
