### ISSUE TITLE
pstsUnderlineColor not working

### ISSUE THREAD

**Issue by IanLeatherbury** [jamesmontemagno/PagerSlidingTabStrip-for-Xamarin.Android#17]
Hey James, 

I was trying to update the underline color on my application and it does not appear to be working.

See this line `app:pstsUnderlineColor="#ffffff"` in the axml below.

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent">
    <com.refractored.PagerSlidingTabStrip
        android:id="@+id/tabs"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:background="?attr/colorPrimary"
        app:pstsPaddingMiddle="false"
        app:pstsShouldExpand="true"
        app:pstsUnderlineColor="#ffffff" />
    <android.support.v4.view.ViewPager
        android:id="@+id/viewPager"
        android:layout_width="fill_parent"
        android:layout_height="0dp"
        android:layout_weight="1" />
</LinearLayout>
```

This is the result: 
![image](https://cloud.githubusercontent.com/assets/5083430/8193243/9592daf2-1428-11e5-82f3-1b25a1ceacad.png)

The underline color matches `<item name="android:textColorPrimary">@color/wet_asphalt</item>` defined in styles.xml.

Additionally I tried 

```
m_PageIndicator = view.FindViewById<PagerSlidingTabStrip>(Resource.Id.tabs);
m_PageIndicator.UnderlineColor = Resource.Color.white;
```

This also did not work. Any suggestions? Also, per bamboo, happy birthday!

**Comment by IanLeatherbury** [comment]
Ah, also I am running 1.0.9.2.

**Comment by jamesmontemagno** [comment]
This library has now been deprecated by the new Android Support Design Library. Please see the full component for a sample: https://components.xamarin.com/view/xamandroidsupportdesign
