### ISSUE TITLE
tab layout

### ISSUE THREAD

**Issue by JanickRoss** [jamesmontemagno/PagerSlidingTabStrip-for-Xamarin.Android#18]
With an AppCompatActivity is possible to make a tablayout without use a custom lib or object as PagerSlindingTabStrip ? Xamarin have a buildin solution ?

**Comment by martijn00** [comment]
You can find samples of a plain Xamarin Implementation here: https://github.com/xamarin/monodroid-samples/tree/master/android5.0/Cheesesquare

For MvvmCross you can use this: https://github.com/MvvmCross/MvvmCross-AndroidSupport/tree/master/Samples

**Comment by jamesmontemagno** [comment]
Please grab the component: https://components.xamarin.com/view/xamandroidsupportdesign
