### ISSUE TITLE
ViewPager how to fill in the edge?

### ISSUE THREAD

**Issue by xlievo** [jamesmontemagno/PagerSlidingTabStrip-for-Xamarin.Android#19]
![qq1](https://cloud.githubusercontent.com/assets/5188470/9405720/d92e1460-482c-11e5-910f-fdcde21889af.png)

```
                                                            Thank you!
```

**Comment by jamesmontemagno** [comment]
I am not sure exactly what you mean here. Your fragment will need to fill parent.

**Comment by xlievo** [comment]
CardView problem
Have been settled 
       Thank you!
