### ISSUE TITLE
Crash on resume on Jelly Bean device

### ISSUE THREAD

**Issue by jorgenstorlie** [jamesmontemagno/PagerSlidingTabStrip-for-Xamarin.Android#2]
I have a problem that the sample app is crashing after it have been sent to background on my Jelly Bean device. It works on Lollipop.

Steps to reproduce:
Run the sample app
Switch to some other apps
After a while the sample app is put into background
Switch back to the app and it crashes.

It would be nice if some other than me can reproduce  this.

**Comment by jorgenstorlie** [comment]
Maybe the  same as in

https://github.com/LordZoltan/PagerSlidingTabStrip.Net/tree/master/PagerSlidingTabStrip

The behavior is the same .

OnRestoreInstanceState crash fix (1.1.40303.1428) 
The Tab Strip state save/restore did not work correctly and would cause
a low-level crash when restoring an activity that had previously been
destroyed.  If you use dev tools on a device and enable the 'Don't Keep
Activities' option you can easily reproduce by pressing home from an
activity that has the tab strip, and then switching back to the app
again.

Turns out the nested SavedState implementation was being ignored
completely and despite my best efforts, I could not get it to work.
Changed it over to using a Bundle instead and it all appears to work
correctly now.

**Comment by jamesmontemagno** [comment]
Integrated into 1.0.9 beta 3
