### ISSUE TITLE
Remove Fragment from Activity, crashing

### ISSUE THREAD

**Issue by robobat** [jamesmontemagno/PagerSlidingTabStrip-for-Xamarin.Android#21]
Hello, 

In my activity I have a fragment on the left with a list view (FragmentA) and a fragment on the right which contains a PagerSlidingTabStrip (FragmentB).  Depending on the layout, I add them differently.  They both add to the layout correctly, and FragmentA can be removed correctly, but when I go to remove the FragmentB, the app crashes and I get a java.lang.reflect.InvocationTargetException.  Is there something I need to add in the Fragment to handle being destroyed?  Do you have a sample app that shows the SlidingTabs being contained in a fragment themselves?

Thanks in advance

**Comment by jamesmontemagno** [comment]
Please upgrade to the : https://components.xamarin.com/view/xamandroidsupportdesign  as this is now deprecated. Thanks :)
