### ISSUE TITLE
Resource.designer.cs does not contain definition

### ISSUE THREAD

**Issue by arthurliebhardt** [jamesmontemagno/PagerSlidingTabStrip-for-Xamarin.Android#23]
Hello i have following problem my resource designer doesn't find these dimensions from the PagerSlidingTabStrip Plugin. Im building the project on SDK 23.

```
global::com.refractored.Resource.Dimension.dialog_fixed_height_major = global::Test.Droid.Resource.Dimension.dialog_fixed_height_major;
            global::com.refractored.Resource.Dimension.dialog_fixed_height_minor = global::Test.Droid.Resource.Dimension.dialog_fixed_height_minor;
            global::com.refractored.Resource.Dimension.dialog_fixed_width_major = global::Test.Droid.Resource.Dimension.dialog_fixed_width_major;
            global::com.refractored.Resource.Dimension.dialog_fixed_width_minor = global::Test.P4V.Droid.Resource.Dimension.dialog_fixed_width_minor;
```

Compile is set to API 23 and Export.dll is added to Reference.

The sample project from you shows me the exact same error.

i tried to find a solution changed the SDK's but nothing helped.

Best Regards

**Comment by jamesmontemagno** [comment]
I have updated to the latest latest 23.1.1.0 and have my sample building. Take a look now.

I published new nugets.

**Comment by arthurliebhardt** [comment]
Yea it's working, Thank you very much
