### ISSUE TITLE
Centered Tab Strip with tri-angular Indicator

### ISSUE THREAD

**Issue by glalwani2** [jamesmontemagno/PagerSlidingTabStrip-for-Xamarin.Android#24]
Hi I want the seledted tab to be in center with tri - angular indicator for the selected tab. Which attribute I have to set to make it work.

**Comment by jamesmontemagno** [comment]
This library has now been deprecated by the new Android Support Design Library. Please see the full component for a sample: https://components.xamarin.com/view/xamandroidsupportdesign
