### ISSUE TITLE
Undefined reference in Resources.cs

### ISSUE THREAD

**Issue by ghost** [jamesmontemagno/PagerSlidingTabStrip-for-Xamarin.Android#25]
Using the latest AppCompat there are 110 undefined references. A fix is to do:

``` diff
+ global::com.refractored.Resource.Styleable.Theme = global::App.Name.Resource.Styleable.Theme
- global::com.refractored.Resource.Styleable.Theme = global::App.Name.Resource.Styleable.AppCompatTheme
```

For all instances, every time the Resources.designer.cs is regenerated.

I'm not sure how to go about fixing it in your component however.

**Comment by jamesmontemagno** [comment]
Which version did you install?

**Comment by jamesmontemagno** [comment]
Will ship 2 new versions. 1 against 23.3 and 1 against 23.4

**Comment by ghost** [comment]
I'm using the one from NuGet which is version 1.0.9.
