### ISSUE TITLE
Crash when saving.  Can't find PutInt

### ISSUE THREAD

**Issue by kjeremy** [jamesmontemagno/PagerSlidingTabStrip-for-Xamarin.Android#7]
I just upgraded to to 1.0.9 and the app crashes in `ActionbarActivity.OnSaveInstanceState`.

It looks like `Android.OS.BaseBundle` is only present on API 21+

```
04-14 14:19:49.762 W/        (27117): Missing method PutInt in assembly Refractored.PagerSlidingTabStrip.dll, type Android.OS.BaseBundle
04-14 14:19:49.762 W/Mono    (27117): The class Android.OS.BaseBundle could not be loaded, used in Refractored.PagerSlidingTabStrip
Unhandled Exception:

System.TypeLoadException: Could not load type 'Android.OS.BaseBundle' from assembly 'Refractored.PagerSlidingTabStrip'.
```

**Comment by kjeremy** [comment]
Deleting my bin and obj directories seems to have fixed this.

**Comment by kjeremy** [comment]
This still occurs when I transition to another activity.

**Comment by kjeremy** [comment]
Note that I am compiling against 17 but targetting 21.

`<uses-sdk android:minSdkVersion="17" android:targetSdkVersion="21" />`

**Comment by kjeremy** [comment]
Bah.  I had to set my app's target framework version to 21 and now the problem has gone away.  Maybe that should be specified in the README.md?

**Comment by jamesmontemagno** [comment]
Added! Sorry about that, you must compile against 21 as I am using API 21 specific things. This is also just best practice to compile against your target. Here is a great breakdown: http://redth.codes/such-android-api-levels-much-confuse-wow/
