### ISSUE TITLE
I want to change tab indicator from triangle icon to default tab indicator. How can i achieve this?

### ISSUE THREAD

**Issue by MeenaxiD** [jamesmontemagno/PagerSlidingTabStrip-for-Xamarin.Android#9]

**Comment by jamesmontemagno** [comment]
Do you have a photo or screenshot of what you are talking about? I don't think we have any triangle icons at all.. Let me know.

**Comment by MeenaxiD** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/11550768/7343161/7c013e54-ecdb-11e4-9a92-664d68706adf.png)

**Comment by jamesmontemagno** [comment]
Are you sure you are using the correct nuget library? This library only has the underline as found on the readme page to follow the material design guidelines.

**Comment by hongzhou85** [comment]
Something like this?
https://github.com/kpbird/TriangleTabs
